language: julia
julia:
- 1.1
- nightly
matrix:
  allow_failures:
    - julia: nightly
before_script:
- julia -e 'using Pkg; pkg"add SparseDiffTools#master"'
after_success:    
- julia -e 'using Pkg; cd(Pkg.dir("EconPDEs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  email: false
  on_failure: change